# Name: Calculate the number 8 by adding, subtracting, multiplying and dividing.
# Date: 2024-03-11
# Author: Leo G. Gasteiger

add_eight = 5 + 3
add_message = f"The number eight generated by addition is 5 + 3 = {add_eight}"
print(add_message)

subtr_eight = 18 - 10
subtr_message = f"The number eight generated by subtraction is 18 - 10 = {subtr_eight}"
print(subtr_message)

mult_eight = 4 * 2
mult_message = f"The number eight generated by multiplication is 4 * 2 = {mult_eight}"
print(mult_message)

div_eight = 80 / 10
div_float_message = f"The number eight generated by division in float format is 80 / 10 = {div_eight}"
print(div_float_message)
div_int_message = f"The number eight generated by division in integer format is 80 / 10 = {int(div_eight)}"
print(div_int_message)
